# Generated by Django 4.0.4 on 2022-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_direccion_alter_producto_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
